FROM ubuntu:14.10

# Actualizar Source List
RUN sed -i 's/archive/old-releases/g' /etc/apt/sources.list

# Instalar el cliente de OpenSSH
RUN apt update && apt install -y sudo net-tools openssh-client
