FROM ubuntu:20.10

# Ajustar Source List
RUN sed -i 's/archive/old-releases/g' /etc/apt/sources.list
RUN sed -i '/^deb.*security.ubuntu.com/s/^/#/' /etc/apt/sources.list

# Instalar cliente SSH, servidor SSH y Tshark
RUN apt update && \
    apt install -y sudo net-tools openssh-client openssh-server tshark

# Agregar Usuario Test con contraseña test
RUN useradd -m test && \
    echo 'test:test' | chpasswd

# Abrir puerto 22 para conexiones
EXPOSE 22
