FROM ubuntu:18.10

#Identico a c2 pero con Ubuntu 18.10
RUN sed -i 's/archive/old-releases/g' /etc/apt/sources.list
RUN sed -i '/security.ubuntu.com/s/ˆ/#/' /etc/apt/sources.list 
RUN apt update && apt install -y sudo net-tools openssh-client
